plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.ludorum.app'
    compileSdk 36

    defaultConfig {
        applicationId "fr.ludorum.app"
        minSdk 26
        targetSdk 36
        versionCode 1114
        versionName "1.1.14"
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile(
                'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }
}
